name: Cleanup Caches
on:
  pull_request:
    types:
      - closed

jobs:
    release-notes:
        uses: zaphiro-technologies/github-workflows/.github/workflows/clean-up-storage.yaml@main
        secrets: inherit
