name: Markdown Check

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  markdown-checker:
    uses: zaphiro-technologies/github-workflows/.github/workflows/markdown.yaml@main
    secrets: inherit
