name: Markdown Check

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  markdown-checker:
    uses: zaphiro-technologies/github-workflows/.github/workflows/markdown.yaml@main
    secrets: inherit
